POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstname":"ankur",
    "lastname":"shrivastav",
    "email":"ankurgmail",
    "password":"ankur",
    "confirmpassword":"ankur",
    "contactnumber":"ankur"
}